In [48]:
import torch

In [49]:
import os
os.chdir(r'C:\Users\SANAD\micrograd')
print(os.getcwd())

C:\Users\SANAD\micrograd


In [50]:
words = open('names.txt', 'r').read().splitlines()

In [51]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
print(itos[0])  # should print '.'
print(len(stoi))  # should print 27

.
27


In [52]:
N = torch.zeros((27, 27), dtype=torch.int32)
for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        N[ix1, ix2] += 1

In [53]:
p = N[0].float()
p = p / p.sum()
p

tensor([0.0000, 0.1377, 0.0408, 0.0481, 0.0528, 0.0478, 0.0130, 0.0209, 0.0273,
        0.0184, 0.0756, 0.0925, 0.0491, 0.0792, 0.0358, 0.0123, 0.0161, 0.0029,
        0.0512, 0.0642, 0.0408, 0.0024, 0.0117, 0.0096, 0.0042, 0.0167, 0.0290])

In [54]:
g = torch.Generator().manual_seed(2147483647)
ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
itos[ix]

'c'

In [55]:
g = torch.Generator().manual_seed(2147483647)
p = torch.rand(3, generator=g)
p = p / p.sum()
p

tensor([0.6064, 0.3033, 0.0903])

In [56]:
torch.multinomial(p, num_samples=100, replacement=True, generator=g)

tensor([1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
        0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 1, 0,
        0, 1, 1, 1])

In [57]:
P = N.float()
print(P.shape)  # should print torch.Size([27, 27])
P = P / P.sum(1, keepdim=True)
print(P.shape)  # should print torch.Size([27, 27])

torch.Size([27, 27])
torch.Size([27, 27])


In [58]:
p.shape

torch.Size([3])

In [59]:
P.sum(1,keepdim = True).shape

torch.Size([27, 1])

In [74]:
P[0].sum()

tensor(1.0000)

In [83]:
P=(N+1).float()
P = P/P.sum(1,keepdim= True)

In [84]:
g = torch.Generator().manual_seed(2147483647)
for i in range(10):
    ix = 0
    out = []
    while True:
       # p = N[ix].float()
        #p = p / p.sum()
        p=P[ix]
        #p = torch.ones(27)/27.0
        ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
        if ix == 0:
            out.append('.')
            break
        out.append(itos[ix])
    print(''.join(out))

cexzmmzoglkurkicqzktyhwmvmzimjttainrlkfukzkktda.
sfcxvpubjtbhrmgotzx.
iczixqctvujkwptedogkkjemkmmsidguenkbvgynywftbspmhwcivgbvtahlvsu.
dsdxxblnwglhpyiw.
iva.
jwrpfdwipkwzkm.
desu.
firmt.
gbiksjbquabsvath.
kuysxqevicmrbxmcwyhrrjenvxmvifkmwmghfvjzxobomysox.


In [85]:
N = torch.zeros((27, 27), dtype=torch.int32)
n=0 
log_likelihood = 0.0
for w in words[:3]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        N[ix1, ix2] += 1
        prob = P[ix1,ix2]
        n+=1
        logprob = torch.log(prob)
        log_likelihood += logprob
       # print(f'{ch1,ch2}:{prob:4f}logprob:{logprob:.4f}')
print(f'{log_likelihood = }')
nll = -log_likelihood
print(f'{nll =}')
print(f'{nll/n}')

log_likelihood = tensor(-40.9701)
nll =tensor(40.9701)
2.5606331825256348
