In [2]:
import torch

In [3]:
import os
os.chdir(r'C:\Users\SANAD\micrograd')
print(os.getcwd())

C:\Users\SANAD\micrograd


In [4]:
words = open('names.txt', 'r').read().splitlines()

In [5]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
print(itos[0])  # should print '.'
print(len(stoi))  # should print 27

.
27


In [6]:
N = torch.zeros((27, 27), dtype=torch.int32)
for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        N[ix1, ix2] += 1

In [7]:
p = N[0].float()
p = p / p.sum()
p

tensor([0.0000, 0.1377, 0.0408, 0.0481, 0.0528, 0.0478, 0.0130, 0.0209, 0.0273,
        0.0184, 0.0756, 0.0925, 0.0491, 0.0792, 0.0358, 0.0123, 0.0161, 0.0029,
        0.0512, 0.0642, 0.0408, 0.0024, 0.0117, 0.0096, 0.0042, 0.0167, 0.0290])

In [8]:
g = torch.Generator().manual_seed(2147483647)
ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
itos[ix]

'c'

In [9]:
g = torch.Generator().manual_seed(2147483647)
p = torch.rand(3, generator=g)
p = p / p.sum()
p

tensor([0.6064, 0.3033, 0.0903])

In [10]:
torch.multinomial(p, num_samples=100, replacement=True, generator=g)

tensor([1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
        0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 1, 0,
        0, 1, 1, 1])

In [11]:
P = N.float()
print(P.shape)  # should print torch.Size([27, 27])
P = P / P.sum(1, keepdim=True)
print(P.shape)  # should print torch.Size([27, 27])

torch.Size([27, 27])
torch.Size([27, 27])


In [12]:
p.shape

torch.Size([3])

In [13]:
P.sum(1,keepdim = True).shape

torch.Size([27, 1])

In [14]:
P[0].sum()

tensor(1.)

In [15]:
P=(N+1).float()
P = P/P.sum(1,keepdim= True)

In [16]:
g = torch.Generator().manual_seed(2147483647)
for i in range(10):
    ix = 0
    out = []
    while True:
       # p = N[ix].float()
        #p = p / p.sum()
        p=P[ix]
        #p = torch.ones(27)/27.0
        ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
        if ix == 0:
            out.append('.')
            break
        out.append(itos[ix])
    print(''.join(out))

cexze.
momasurailezitynn.
konimittain.
llayn.
ka.
da.
staiyaubrtthrigotai.
moliellavo.
ke.
teda.


In [17]:
N = torch.zeros((27, 27), dtype=torch.int32)
n=0 
log_likelihood = 0.0
for w in words[:3]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        N[ix1, ix2] += 1
        prob = P[ix1,ix2]
        n+=1
        logprob = torch.log(prob)
        log_likelihood += logprob
       # print(f'{ch1,ch2}:{prob:4f}logprob:{logprob:.4f}')
print(f'{log_likelihood = }')
nll = -log_likelihood
print(f'{nll =}')
print(f'{nll/n}')

log_likelihood = tensor(-38.8086)
nll =tensor(38.8086)
2.4255354404449463


In [27]:
xs , ys = [] , []
for w in words[:1]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        xs.append(ix1)
        ys.append(ix2)
xs = torch.tensor(xs)
ys = torch.tensor(ys)

In [29]:
xs


tensor([ 0,  5, 13, 13,  1])

In [30]:
ys

tensor([ 5, 13, 13,  1,  0])

In [33]:
import torch.nn.functional as F

In [38]:
xenc = F.one_hot(xs,num_classes = 27).float()
xenc

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
xenc.shape

torch.Size([5, 27])

In [40]:
xenc.dtype

torch.float32

In [44]:
W = torch.randn((27,27))
xenc @ W

tensor([[ 1.1652, -0.0030, -0.4587,  0.3321, -0.4863,  0.3244,  0.7661, -0.1596,
         -0.3069, -1.0760,  1.4473, -0.7725, -0.6278,  1.4377, -0.4154, -0.4739,
         -1.0074, -0.8675, -2.2705, -0.0321, -1.4065, -0.8111, -0.1412,  0.5554,
         -0.0320,  0.7380,  0.3670],
        [ 0.3377, -0.7090,  2.4559, -1.2724,  1.2127,  0.1110,  1.3176, -1.6527,
          0.8316,  0.8548,  0.7789,  1.9190, -0.6618, -0.5161, -0.4707,  0.0286,
          1.3595, -0.6284,  0.5412,  1.1798,  0.5364, -0.6081,  2.9789, -1.0932,
          0.3569, -1.8197, -1.2047],
        [-1.8585,  0.9329,  0.5527,  0.9094,  0.3048,  0.2267, -0.5917,  0.2737,
          0.2120, -0.6973,  0.7631,  1.7641, -1.3041,  0.7641,  1.2032, -0.4212,
          0.9093, -1.8952,  0.0275,  0.2529, -1.3661, -1.2879,  0.2427, -1.5492,
          1.1817, -1.3759,  0.5816],
        [-1.8585,  0.9329,  0.5527,  0.9094,  0.3048,  0.2267, -0.5917,  0.2737,
          0.2120, -0.6973,  0.7631,  1.7641, -1.3041,  0.7641,  1.2032, -0.4212

In [46]:
(xenc @ W)[3,13]

tensor(0.7641)